
# define java compiler & java program
# Note: it would be better to do an absolute path to javac & java
JCC = /usr/bin/javac
JV = /usr/bin/java

# define compilation flag(s)
# -g compiles with debugging information
JFLAGS = -g


# default action of my makefile (because this is first)
#	pre-req is that demo.java exist
#
 default: repeat.java
	$(JCC) $(JFLAGS) repeat.java

# defining target (or command to be used with make) to run my program
run:repeat.class
	$(JV) repeat

# defining target to delete my compiled program
delete:
	rm repeat.class

